modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="maxdogs_lost_artifacts"
version="0.5.0"
displayName="MaxDog's Lost Artifacts"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="MaxDog"

[[dependencies.maxdogs_lost_artifacts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




